apiVersion: kubedb.com/v1alpha2
kind: Elasticsearch
metadata:
  name: es-standalone
  namespace: demo
spec:
  version: 1.12.0-opendistro
  enableSSL: true
  replicas: 1
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: DoNotTerminate