apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: custom-postgres
  namespace: demo
spec:
  version: "10.2-v5"
  configSource:
    configMap:
      name: pg-custom-config
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
