apiVersion: kubedb.com/v1alpha2
kind: MariaDB
metadata:
  name: mariadb-init-script
  namespace: demo
spec:
  version: "8.0.21"
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  init:
    script:
      configMap:
        name: my-init-script
